apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nginx-secret
  namespace: nginx
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: aws-secretsstore
    kind: ClusterSecretStore
  target:
    name: nginx-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: demo-nginx
        property: DEMO_USERNAME
    - secretKey: password
      remoteRef:
        key: demo-nginx
        property: DEMO_PASSWORD 